version: '3.8'

services:
  wordpress:
    build: .
    ports:
      - "8000:80"
    volumes:
      - ./wp-content:/var/www/html/wp-content
    environment:
      WORDPRESS_DB_HOST: "${DB_HOST}"
      WORDPRESS_DB_NAME: "${DB_NAME}"
      WORDPRESS_DB_USER: "${DB_USER}"
      WORDPRESS_DB_PASSWORD: "${DB_PASSWORD}"
      WORDPRESS_TABLE_PREFIX: "${DB_PREFIX:-wp_}"
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME', 'http://172.20.10.4:8000');
        define('WP_SITEURL', 'http://172.20.10.4:8000');
    restart: unless-stopped
